#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 30

#undef TAPPING_TERM
#define TAPPING_TERM 280

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 10

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 80

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 12

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 60

#define SERIAL_NUMBER "6yRNB/ZPKzw7"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

